services:
  db:
    image: postgres:15
    container_name: iot_postgres_db
    restart: always
    environment:
      POSTGRES_USER: Vukasin
      POSTGRES_PASSWORD: 18972
      POSTGRES_DB: iot_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Vukasin -d iot_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  rest-service:
    build: ./rest-service
    container_name: fastapi_rest_service
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://Vukasin:18972@db:5432/iot_db
    depends_on:
      db:
        condition: service_healthy 

  grpc-service:
    build: ./grpc-service
    container_name: node_grpc_service
    restart: always
    ports:
      - "50051:50051"
    environment:
      - DATABASE_URL=postgresql://Vukasin:18972@db:5432/iot_db
    depends_on:
      db:
        condition: service_healthy

  graphql-service:
    build: ./graphql-service
    container_name: fastapi_graphql_service
    restart: always
    ports:
      - "8001:8001" 
    environment:
      - DATABASE_URL=postgresql://Vukasin:18972@db:5432/iot_db
    depends_on:
      db:
        condition: service_healthy

  k6:
    image: grafana/k6
    container_name: k6_test_runner
    profiles:
      - test
    volumes:
      - .:/apps
    working_dir: /apps
    command: run k6-test.js