services:
  
  postgres_db:
    image: postgres:15
    container_name: iot_postgres_db_p2
    environment:
      POSTGRES_USER: vukasin
      POSTGRES_PASSWORD: iotpassword
      POSTGRES_DB: iot_p2_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_p2_data:/var/lib/postgresql/data
    networks:
      - iot_network

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: iot_mosquitto_p2
    ports:
      - "1883:1883" 
      - "9001:9001" 
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - iot_network

  kafka:
    image: apache/kafka:3.7.0
    container_name: iot_kafka_p2
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_LOG4J_LOGGERS: "kafka.authorizer.logger=WARN,kafka.server=WARN,org.apache.kafka=WARN"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - iot_network


  ingestion_service:
    build: ./ingestion-service
    container_name: iot_ingestion_p2
    ports:
      - "3000:3000" 
    environment:
      - BROKER_TYPE=mqtt # kafka/mqtt
      - MQTT_QOS=0
      - KAFKA_ACKS=1
    volumes:
      - ./intel_data.json:/app/intel_data.json
    depends_on:
      - mosquitto
      - kafka
    networks:
      - iot_network

  analytics_service:
    build: ./analytics-service
    container_name: iot_analytics_p2
    environment:
      - BROKER_TYPE=mqtt # kafka/mqtt
      - PYTHONUNBUFFERED=1
    ports:
      - "8001:8001"
    depends_on:
      - mosquitto
      - kafka
    networks:
      - iot_network

  storage_service:
    build: ./storage-service
    container_name: iot_storage_p2
    environment:
      - BROKER_TYPE=mqtt # kafka/mqtt
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
      - mosquitto
      - kafka
    networks:
      - iot_network


  k6:
    build:
      context: .
      dockerfile: Dockerfile.k6
    container_name: iot_k6_p2
    profiles:
      - tools
    volumes:
      - ./:/apps
    command: run /apps/k6-test.js
    environment:
      - GRPC_URL=node_grpc_service:50051
      - STORAGE_URL=http://storage_service:8000
      - ANALYTICS_URL=http://analytics_service:8001
    depends_on:
      - postgres_db
      - storage_service
      - analytics_service
    networks:
      - iot_network

networks:
  iot_network:
    name: iot_p2_network
    driver: bridge

volumes:
  postgres_p2_data: